create extension if not exists pgcrypto;
do $$ begin create type public.user_role as enum ('gerente','administrativo','visualizador'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade, full_name text not null, email text, role public.user_role not null default 'visualizador', created_at timestamptz default now());
alter table public.profiles add column if not exists email text;
create table if not exists public.clients(id uuid primary key default gen_random_uuid(), name text not null, phone text, email text, document text, created_at timestamptz default now());
create table if not exists public.vehicles(id uuid primary key default gen_random_uuid(), client_id uuid references public.clients(id) on delete cascade, plate text not null unique, brand text, model text, color text, year text, created_at timestamptz default now());
create table if not exists public.service_types(id uuid primary key default gen_random_uuid(), name text not null, description text, price numeric(12,2) not null default 0, discount_percent numeric(5,2) not null default 0 check(discount_percent between 0 and 100), active boolean default true, created_at timestamptz default now());
create table if not exists public.employees(id uuid primary key default gen_random_uuid(), name text not null, phone text, position text, commission_percent numeric(5,2) not null default 0 check(commission_percent between 0 and 100), active boolean default true, created_at timestamptz default now());
create table if not exists public.payment_methods(id uuid primary key default gen_random_uuid(), name text not null unique, active boolean default true, created_at timestamptz default now());
create table if not exists public.service_orders(id uuid primary key default gen_random_uuid(), vehicle_id uuid references public.vehicles(id), service_id uuid references public.service_types(id), employee_id uuid references public.employees(id), performed_by text, notes text, status text not null default 'concluido', charged_amount numeric(12,2), completed_at timestamptz, created_at timestamptz default now(), created_by uuid references auth.users(id));
create table if not exists public.service_images(id uuid primary key default gen_random_uuid(), service_order_id uuid references public.service_orders(id) on delete cascade, image_url text not null, file_name text, created_at timestamptz default now());
create table if not exists public.appointments(id uuid primary key default gen_random_uuid(), client_id uuid references public.clients(id), vehicle_id uuid references public.vehicles(id), service_id uuid references public.service_types(id), scheduled_at timestamptz not null, status text not null default 'agendado', notes text, created_at timestamptz default now(), created_by uuid references auth.users(id));
create table if not exists public.payments(id uuid primary key default gen_random_uuid(), service_order_id uuid references public.service_orders(id), payment_method_id uuid references public.payment_methods(id), amount numeric(12,2) not null default 0, paid_at timestamptz default now(), created_by uuid references auth.users(id));
create table if not exists public.cash_closings(id uuid primary key default gen_random_uuid(), closing_date date not null unique, total_amount numeric(12,2) not null default 0, details jsonb default '[]'::jsonb, closed_at timestamptz default now(), closed_by uuid references auth.users(id));
create table if not exists public.audit_logs(id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id), action text not null, entity_type text, entity_id uuid, created_at timestamptz default now());

alter table public.service_orders add column if not exists employee_id uuid references public.employees(id);
alter table public.service_orders add column if not exists status text not null default 'concluido';
alter table public.service_orders add column if not exists charged_amount numeric(12,2);
alter table public.service_orders add column if not exists completed_at timestamptz;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,email,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email),new.email,'visualizador') on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.current_role() returns public.user_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid(); $$;

drop view if exists public.audit_logs_view;
create view public.audit_logs_view with (security_invoker=true) as select a.*,p.full_name as user_name from public.audit_logs a left join public.profiles p on p.id=a.user_id;

alter table public.profiles enable row level security; alter table public.clients enable row level security; alter table public.vehicles enable row level security; alter table public.service_types enable row level security; alter table public.service_orders enable row level security; alter table public.service_images enable row level security; alter table public.audit_logs enable row level security; alter table public.appointments enable row level security; alter table public.employees enable row level security; alter table public.payment_methods enable row level security; alter table public.payments enable row level security; alter table public.cash_closings enable row level security;

do $$ declare r record; begin for r in select policyname,tablename from pg_policies where schemaname='public' and tablename in ('profiles','clients','vehicles','service_types','service_orders','service_images','audit_logs','appointments','employees','payment_methods','payments','cash_closings') loop execute format('drop policy if exists %I on public.%I',r.policyname,r.tablename); end loop; end $$;
create policy "read profiles" on public.profiles for select to authenticated using(id=auth.uid() or public.current_role()='gerente'); create policy "manager profiles" on public.profiles for update to authenticated using(public.current_role()='gerente') with check(public.current_role()='gerente');
create policy "read clients" on public.clients for select to authenticated using(true); create policy "write clients" on public.clients for all to authenticated using(public.current_role() in ('gerente','administrativo')) with check(public.current_role() in ('gerente','administrativo'));
create policy "read vehicles" on public.vehicles for select to authenticated using(true); create policy "write vehicles" on public.vehicles for all to authenticated using(public.current_role() in ('gerente','administrativo')) with check(public.current_role() in ('gerente','administrativo'));
create policy "read services" on public.service_types for select to authenticated using(true); create policy "manager services" on public.service_types for all to authenticated using(public.current_role()='gerente') with check(public.current_role()='gerente');
create policy "read employees" on public.employees for select to authenticated using(true); create policy "manager employees" on public.employees for all to authenticated using(public.current_role()='gerente') with check(public.current_role()='gerente');
create policy "read payment methods" on public.payment_methods for select to authenticated using(true); create policy "manager payment methods" on public.payment_methods for all to authenticated using(public.current_role()='gerente') with check(public.current_role()='gerente');
create policy "read orders" on public.service_orders for select to authenticated using(true); create policy "write orders" on public.service_orders for all to authenticated using(public.current_role() in ('gerente','administrativo')) with check(public.current_role() in ('gerente','administrativo'));
create policy "read images" on public.service_images for select to authenticated using(true); create policy "write images" on public.service_images for all to authenticated using(public.current_role() in ('gerente','administrativo')) with check(public.current_role() in ('gerente','administrativo'));
create policy "read appointments" on public.appointments for select to authenticated using(true); create policy "write appointments" on public.appointments for all to authenticated using(public.current_role() in ('gerente','administrativo')) with check(public.current_role() in ('gerente','administrativo'));
create policy "read payments" on public.payments for select to authenticated using(true); create policy "write payments" on public.payments for all to authenticated using(public.current_role() in ('gerente','administrativo')) with check(public.current_role() in ('gerente','administrativo'));
create policy "read closings" on public.cash_closings for select to authenticated using(true); create policy "manager closings" on public.cash_closings for all to authenticated using(public.current_role()='gerente') with check(public.current_role()='gerente');
create policy "read audit" on public.audit_logs for select to authenticated using(public.current_role()='gerente'); create policy "insert audit" on public.audit_logs for insert to authenticated with check(auth.uid()=user_id);

insert into public.payment_methods(name) values('Dinheiro'),('PIX'),('Cartão de débito'),('Cartão de crédito') on conflict(name) do nothing;
insert into storage.buckets(id,name,public) values('service-images','service-images',true) on conflict do nothing;
drop policy if exists "service images authenticated upload" on storage.objects; drop policy if exists "service images public read" on storage.objects;
create policy "service images authenticated upload" on storage.objects for insert to authenticated with check(bucket_id='service-images');
create policy "service images public read" on storage.objects for select using(bucket_id='service-images');
