import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {
 Car,Users,Wrench,ClipboardList,ShieldCheck,LogOut,Plus,Camera,Trash2,Edit3,
 CalendarDays,Wallet,UserRoundCog,FileDown,MessageCircle,Eye,X,CheckCircle2,
 Clock3,CreditCard,Percent,Image as ImageIcon,Save,Search
} from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import './styles.css';

const url=import.meta.env.VITE_SUPABASE_URL;
const key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=(url&&key)?createClient(url,key):null;
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const dt=v=>v?new Date(v).toLocaleString('pt-BR'):'-';
const dateOnly=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'-';
const finalPrice=s=>Number(s?.price||0)*(1-Number(s?.discount_percent||0)/100);
const safePhone=p=>String(p||'').replace(/\D/g,'');

function App(){
 const [session,setSession]=useState(undefined),[profile,setProfile]=useState(undefined),[tab,setTab]=useState('dashboard');
 const [clients,setClients]=useState([]),[vehicles,setVehicles]=useState([]),[services,setServices]=useState([]),[orders,setOrders]=useState([]),[images,setImages]=useState([]),[logs,setLogs]=useState([]);
 const [appointments,setAppointments]=useState([]),[employees,setEmployees]=useState([]),[paymentMethods,setPaymentMethods]=useState([]),[payments,setPayments]=useState([]),[cashClosings,setCashClosings]=useState([]),[profiles,setProfiles]=useState([]);
 const [login,setLogin]=useState({email:'',password:''}),[error,setError]=useState(''),[loadingData,setLoadingData]=useState(false),[profileError,setProfileError]=useState('');
 const configured=Boolean(supabase);

 useEffect(()=>{
  if(!configured){setSession(null);return;}
  let mounted=true;
  supabase.auth.getSession().then(({data,error})=>{
   if(!mounted)return;
   if(error){setError(error.message);setSession(null);return;}
   setSession(data.session||null);
  });
  const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,nextSession)=>{
   if(mounted)setSession(nextSession||null);
  });
  return()=>{mounted=false;subscription.unsubscribe();};
 },[configured]);

 useEffect(()=>{
  if(session?.user&&configured)loadAll();
  if(session===null){setProfile(undefined);setProfileError('');}
 },[session?.user?.id,configured]);

 async function loadAll(){
  if(!supabase||!session?.user)return;
  setLoadingData(true);setProfileError('');
  try{
   const {data:p,error:pErr}=await supabase.from('profiles').select('*').eq('id',session.user.id).maybeSingle();
   if(pErr)throw pErr;
   if(!p){
    setProfile(null);
    setProfileError('Sua conta existe no Authentication, mas não possui um perfil no sistema. Execute novamente o schema.sql no Supabase ou corrija o cadastro em public.profiles.');
    return;
   }
   setProfile(p);
   const q=await Promise.all([
    supabase.from('clients').select('*').order('created_at',{ascending:false}),supabase.from('vehicles').select('*').order('created_at',{ascending:false}),supabase.from('service_types').select('*').order('name'),
    supabase.from('service_orders').select('*').order('created_at',{ascending:false}),supabase.from('service_images').select('*').order('created_at',{ascending:false}),supabase.from('audit_logs_view').select('*').order('created_at',{ascending:false}).limit(250),
    supabase.from('appointments').select('*').order('scheduled_at'),supabase.from('employees').select('*').order('name'),supabase.from('payment_methods').select('*').order('name'),supabase.from('payments').select('*').order('paid_at',{ascending:false}),
    supabase.from('cash_closings').select('*').order('closed_at',{ascending:false}),supabase.from('profiles').select('*').order('full_name')
   ]);
   const firstError=q.find(x=>x.error)?.error;if(firstError)throw firstError;
   setClients(q[0].data||[]);setVehicles(q[1].data||[]);setServices(q[2].data||[]);setOrders(q[3].data||[]);setImages(q[4].data||[]);setLogs(q[5].data||[]);
   setAppointments(q[6].data||[]);setEmployees(q[7].data||[]);setPaymentMethods(q[8].data||[]);setPayments(q[9].data||[]);setCashClosings(q[10].data||[]);setProfiles(q[11].data||[]);
  }catch(e){setProfileError(e.message||'Não foi possível carregar os dados do sistema.');}
  finally{setLoadingData(false);}
 }

 async function signIn(e){
  e.preventDefault();setError('');
  if(!supabase)return;
  if(!login.email.trim()||!login.password){setError('Informe e-mail e senha.');return;}
  const {error}=await supabase.auth.signInWithPassword({email:login.email.trim(),password:login.password});
  if(error)setError(error.message==='Invalid login credentials'?'E-mail ou senha inválidos.':error.message);
 }
 async function signOut(){if(supabase)await supabase.auth.signOut();setSession(null);setProfile(undefined);setTab('dashboard');}
 async function addLog(action,entity_type='',entity_id=null){if(!supabase||!session?.user)return;await supabase.from('audit_logs').insert({user_id:session.user.id,action,entity_type,entity_id});}
 async function insert(table,payload,setter,label){const {data,error}=await supabase.from(table).insert(payload).select().single();if(error){alert(error.message);return null}setter(x=>[data,...x]);await addLog(label,table,data.id);return data}
 async function update(table,id,payload,setter,label){const {data,error}=await supabase.from(table).update(payload).eq('id',id).select().single();if(error){alert(error.message);return false}setter(x=>x.map(r=>r.id===id?data:r));await addLog(label,table,id);return true}
 async function remove(table,id,setter,label){if(!confirm('Tem certeza que deseja excluir este registro? Esta ação não poderá ser desfeita.'))return false;const {error}=await supabase.from(table).delete().eq('id',id);if(error){alert(error.message);return false}setter(x=>x.filter(r=>r.id!==id));await addLog(label,table,id);return true}
 async function uploadImages(orderId,files){if(!files?.length)return;
  for(const file of files){const path=`${orderId}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await supabase.storage.from('service-images').upload(path,file);if(up.error){alert(up.error.message);continue}const {data:{publicUrl}}=supabase.storage.from('service-images').getPublicUrl(path);const {data}=await supabase.from('service_images').insert({service_order_id:orderId,image_url:publicUrl,file_name:file.name}).select().single();if(data)setImages(x=>[data,...x])}
 }

 if(!configured)return <ConfigError/>;
 if(session===undefined)return <Splash message="Verificando sessão..."/>;
 if(!session)return <Login login={login} setLogin={setLogin} signIn={signIn} error={error}/>;
 if(profile===undefined&&loadingData)return <Splash message="Carregando seu perfil..."/>;
 if(profileError||profile===null)return <AccessError message={profileError} signOut={signOut} reload={loadAll}/>;
 if(!profile)return <Splash message="Carregando sistema..."/>;

 const role=profile.role,canWrite=['gerente','administrativo'].includes(role),canAdmin=role==='gerente';
 const common={clients,vehicles,services,orders,images,appointments,employees,paymentMethods,payments,cashClosings,profiles,canWrite,canAdmin,demo:false,profile,supabase,insert,update,remove,addLog,uploadImages,reload:loadAll};
 return <div className="app"><Sidebar tab={tab} setTab={setTab} role={role} signOut={signOut}/><main><header><div><h1>Estética Veicular</h1><p>{profile.full_name||session.user.email} · <b>{role}</b></p></div></header>
  {tab==='dashboard'&&<Dashboard {...common}/>} {tab==='clientes'&&<Clients {...common} setClients={setClients}/>} {tab==='veiculos'&&<Vehicles {...common} setVehicles={setVehicles}/>} {tab==='servicos'&&canAdmin&&<Services {...common} setServices={setServices}/>} {tab==='historico'&&<History {...common} setOrders={setOrders} setPayments={setPayments}/>} {tab==='agendamentos'&&<Appointments {...common} setAppointments={setAppointments}/>} {tab==='equipe'&&canAdmin&&<Employees {...common} setEmployees={setEmployees}/>} {tab==='caixa'&&canAdmin&&<Cash {...common} setPayments={setPayments} setCashClosings={setCashClosings} setPaymentMethods={setPaymentMethods}/>} {tab==='relatorios'&&canAdmin&&<Reports {...common}/>} {tab==='usuarios'&&canAdmin&&<UsersPanel {...common} setProfiles={setProfiles}/>} {tab==='auditoria'&&canAdmin&&<Audit logs={logs}/>} 
 </main></div>
}

function Splash({message}){return <div className="login"><div className="splashCard"><div className="brand"><Car size={34}/><span>Estética Veicular</span></div><div className="spinner"/><p>{message}</p></div></div>}
function ConfigError(){return <div className="login"><div className="configCard"><div className="brand"><Car size={34}/><span>Estética Veicular</span></div><h2>Configuração do Supabase necessária</h2><p>O sistema não encontrou <b>VITE_SUPABASE_URL</b> e/ou <b>VITE_SUPABASE_ANON_KEY</b>.</p><p>Confira o arquivo <code>.env</code> na pasta principal do projeto e reinicie o comando <code>npm run dev</code>.</p><div className="error">Por segurança, o painel não abre sem autenticação.</div></div></div>}
function AccessError({message,signOut,reload}){return <div className="login"><div className="configCard"><div className="brand"><ShieldCheck size={34}/><span>Conta não liberada</span></div><h2>Não foi possível carregar seu perfil</h2><p>{message}</p><div className="inline"><button className="primary" onClick={reload}>Tentar novamente</button><button className="secondary" onClick={signOut}>Sair</button></div></div></div>}

function Login({login,setLogin,signIn,error}){return <div className="login"><form onSubmit={signIn}><div className="brand"><Car size={34}/><span>Estética Veicular</span></div><h2>Acesso ao sistema</h2><p className="loginIntro">Entre com seu usuário autorizado.</p><input type="email" autoComplete="username" required placeholder="E-mail" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/><input type="password" autoComplete="current-password" required placeholder="Senha" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/>{error&&<div className="error">{error}</div>}<button type="submit">Entrar</button><small>O acesso é obrigatório. Usuários e permissões são controlados pelo gerente.</small></form></div>}
function Sidebar({tab,setTab,role,signOut}){const all=[['dashboard',ClipboardList,'Dashboard'],['clientes',Users,'Clientes'],['veiculos',Car,'Veículos'],['servicos',Wrench,'Serviços'],['historico',ClipboardList,'Histórico'],['agendamentos',CalendarDays,'Agendamentos'],['equipe',UserRoundCog,'Equipe'],['caixa',Wallet,'Caixa'],['relatorios',FileDown,'Relatórios'],['usuarios',ShieldCheck,'Usuários'],['auditoria',ShieldCheck,'Auditoria']];const managerOnly=new Set(['servicos','equipe','caixa','relatorios','usuarios','auditoria']);const items=all.filter(([id])=>role==='gerente'||!managerOnly.has(id));return <aside><div className="logo"><div className="mark">EV</div><div><b>ESTÉTICA</b><span>VEICULAR</span></div></div><nav>{items.map(([id,I,l])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><I size={19}/>{l}</button>)}</nav><div className="asideBottom"><span>Perfil: {role}</span><button onClick={signOut}><LogOut size={18}/>Sair</button></div></aside>}
function Dashboard({clients,vehicles,services,orders,appointments,payments}){const today=new Date().toISOString().slice(0,10);const todayOrders=orders.filter(o=>String(o.created_at).slice(0,10)===today);const revenue=payments.reduce((s,p)=>s+Number(p.amount||0),0);return <section><div className="cards"><Card t="Clientes" v={clients.length}/><Card t="Veículos" v={vehicles.length}/><Card t="Agendamentos" v={appointments.filter(a=>a.status==='agendado').length}/><Card t="Serviços hoje" v={todayOrders.length}/><Card t="Faturamento registrado" v={money(revenue)}/></div><Panel title="Próximos agendamentos"><Table headers={['Data/Hora','Cliente','Veículo','Serviço','Status']}>{appointments.slice(0,8).map(a=><tr key={a.id}><td>{dt(a.scheduled_at)}</td><td>{clients.find(c=>c.id===a.client_id)?.name||'-'}</td><td>{vehicles.find(v=>v.id===a.vehicle_id)?.plate||'-'}</td><td>{services.find(s=>s.id===a.service_id)?.name||'-'}</td><td><Status value={a.status}/></td></tr>)}</Table></Panel></section>}
function Card({t,v}){return <div className="card"><span>{t}</span><strong>{v}</strong></div>}
function Status({value}){return <span className={`status ${value}`}>{String(value||'-').replaceAll('_',' ')}</span>}

function Clients({clients,canWrite,insert,update,remove,setClients}){const empty={name:'',phone:'',email:'',document:''};const [f,setF]=useState(empty),[edit,setEdit]=useState(null);async function save(){if(!f.name)return alert('Informe o nome do cliente.');if(edit)await update('clients',edit,{...f},setClients,'Editou cliente');else await insert('clients',f,setClients,'Cadastrou cliente');setF(empty);setEdit(null)}return <section><Panel title="Clientes" action={canWrite&&<button className="primary" onClick={save}><Save size={17}/>{edit?'Salvar edição':'Cadastrar'}</button>}><FormGrid f={f} setF={setF} fields={[['name','Nome completo'],['phone','Telefone'],['email','E-mail'],['document','CPF/CNPJ']]}/>{edit&&<button className="linkBtn" onClick={()=>{setEdit(null);setF(empty)}}>Cancelar edição</button>}<Table headers={['Nome','Telefone','E-mail','Documento','Ações']}>{clients.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.phone||'-'}</td><td>{r.email||'-'}</td><td>{r.document||'-'}</td><td>{canWrite&&<Actions onEdit={()=>{setEdit(r.id);setF({name:r.name||'',phone:r.phone||'',email:r.email||'',document:r.document||''})}} onDelete={()=>remove('clients',r.id,setClients,'Excluiu cliente')}/>}</td></tr>)}</Table></Panel></section>}

function Vehicles({vehicles,clients,orders,services,images,canWrite,insert,update,remove,setVehicles}){const empty={client_id:'',plate:'',brand:'',model:'',color:'',year:''};const [f,setF]=useState(empty),[edit,setEdit]=useState(null),[detail,setDetail]=useState(null);async function save(){if(!f.client_id||!f.plate)return alert('Informe cliente e placa.');if(edit)await update('vehicles',edit,f,setVehicles,'Editou veículo');else await insert('vehicles',f,setVehicles,'Cadastrou veículo');setF(empty);setEdit(null)}const vehicle=vehicles.find(v=>v.id===detail);return <section><Panel title="Veículos" action={canWrite&&<button className="primary" onClick={save}><Save size={17}/>{edit?'Salvar edição':'Cadastrar'}</button>}><div className="formGrid"><select value={f.client_id} onChange={e=>setF({...f,client_id:e.target.value})}><option value="">Cliente</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select>{[['plate','Placa'],['brand','Marca'],['model','Modelo'],['color','Cor'],['year','Ano']].map(([k,p])=><input key={k} placeholder={p} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>)}</div>{edit&&<button className="linkBtn" onClick={()=>{setEdit(null);setF(empty)}}>Cancelar edição</button>}<Table headers={['Placa','Marca/Modelo','Cor','Ano','Cliente','Ações']}>{vehicles.map(r=><tr key={r.id}><td><b>{r.plate}</b></td><td>{r.brand} {r.model}</td><td>{r.color||'-'}</td><td>{r.year||'-'}</td><td>{clients.find(c=>c.id===r.client_id)?.name||'-'}</td><td><Actions onView={()=>setDetail(r.id)} onEdit={canWrite?()=>{setEdit(r.id);setF({client_id:r.client_id||'',plate:r.plate||'',brand:r.brand||'',model:r.model||'',color:r.color||'',year:r.year||''})}:null} onDelete={canWrite?()=>remove('vehicles',r.id,setVehicles,'Excluiu veículo'):null}/></td></tr>)}</Table></Panel>{vehicle&&<VehicleDetail vehicle={vehicle} client={clients.find(c=>c.id===vehicle.client_id)} orders={orders.filter(o=>o.vehicle_id===vehicle.id)} services={services} images={images} onClose={()=>setDetail(null)}/>}</section>}
function VehicleDetail({vehicle,client,orders,services,images,onClose}){return <Modal title={`Veículo ${vehicle.plate}`} onClose={onClose}><div className="detailGrid"><div><b>Cliente</b><span>{client?.name||'-'}</span></div><div><b>Veículo</b><span>{vehicle.brand} {vehicle.model}</span></div><div><b>Cor</b><span>{vehicle.color||'-'}</span></div><div><b>Ano</b><span>{vehicle.year||'-'}</span></div></div><h4>Histórico de serviços</h4>{orders.length===0?<p className="hint">Nenhum serviço registrado.</p>:orders.map(o=>{const pics=images.filter(i=>i.service_order_id===o.id);return <div className="serviceDetail" key={o.id}><div><b>{services.find(s=>s.id===o.service_id)?.name||'Serviço'}</b><span>{dt(o.completed_at||o.created_at)} · {o.performed_by||'-'}</span><p>{o.notes||'Sem observações.'}</p></div>{pics.length>0&&<div className="gallery">{pics.map(i=><a key={i.id} href={i.image_url} target="_blank"><img src={i.image_url}/></a>)}</div>}</div>})}</Modal>}

function Services({services,canAdmin,insert,update,remove,setServices}){const empty={name:'',price:'',discount_percent:'0',description:''};const [f,setF]=useState(empty),[edit,setEdit]=useState(null);async function save(){if(!f.name||f.price==='')return alert('Informe nome e preço.');const p={...f,price:Number(f.price),discount_percent:Number(f.discount_percent||0)};if(edit)await update('service_types',edit,p,setServices,'Editou tipo de serviço');else await insert('service_types',p,setServices,'Cadastrou tipo de serviço');setF(empty);setEdit(null)}return <section><Panel title="Tipos de serviços" action={canAdmin&&<button className="primary" onClick={save}><Save size={17}/>{edit?'Salvar edição':'Cadastrar'}</button>}><FormGrid f={f} setF={setF} fields={[['name','Nome do serviço'],['price','Preço (R$)','number'],['discount_percent','Desconto (%)','number'],['description','Descrição']]}/>{edit&&<button className="linkBtn" onClick={()=>{setEdit(null);setF(empty)}}>Cancelar edição</button>}<Table headers={['Serviço','Preço','Desconto','Preço final','Ações']}>{services.map(r=><tr key={r.id}><td>{r.name}</td><td>{money(r.price)}</td><td>{r.discount_percent||0}%</td><td><b>{money(finalPrice(r))}</b></td><td>{canAdmin&&<Actions onEdit={()=>{setEdit(r.id);setF({name:r.name||'',price:r.price||'',discount_percent:r.discount_percent||0,description:r.description||''})}} onDelete={()=>remove('service_types',r.id,setServices,'Excluiu tipo de serviço')}/>}</td></tr>)}</Table>{!canAdmin&&<p className="hint">Somente o gerente pode cadastrar, editar ou excluir tipos de serviço.</p>}</Panel></section>}

function History({orders,vehicles,services,clients,employees,paymentMethods,payments,images,canWrite,profile,insert,update,uploadImages,setOrders,setPayments}){const empty={vehicle_id:'',service_id:'',employee_id:'',notes:'',status:'concluido',charged_amount:'',payment_method_id:'',files:null};const [f,setF]=useState(empty);async function save(){if(!f.vehicle_id||!f.service_id)return alert('Selecione veículo e serviço.');const sv=services.find(s=>s.id===f.service_id);const amount=Number(f.charged_amount||finalPrice(sv));const row=await insert('service_orders',{vehicle_id:f.vehicle_id,service_id:f.service_id,employee_id:f.employee_id||null,performed_by:profile?.full_name,status:f.status,notes:f.notes,charged_amount:amount,completed_at:f.status==='concluido'?new Date().toISOString():null},setOrders,'Registrou serviço');if(!row)return;if(f.payment_method_id&&f.status==='concluido')await insert('payments',{service_order_id:row.id,payment_method_id:f.payment_method_id,amount,paid_at:new Date().toISOString()},setPayments,'Registrou pagamento');await uploadImages(row.id,f.files);setF(empty)}function whatsapp(o){const v=vehicles.find(x=>x.id===o.vehicle_id),c=clients.find(x=>x.id===v?.client_id),s=services.find(x=>x.id===o.service_id);const phone=safePhone(c?.phone);if(!phone)return alert('Cliente sem telefone cadastrado.');const msg=encodeURIComponent(`Olá, ${c?.name||''}! Seu veículo ${v?.brand||''} ${v?.model||''} (${v?.plate||''}) concluiu o serviço de ${s?.name||'estética veicular'}. Já pode ser retirado. Obrigado!`);window.open(`https://wa.me/55${phone}?text=${msg}`,'_blank')}
 return <section><Panel title="Registrar serviço realizado" action={canWrite&&<button className="primary" onClick={save}><Plus size={17}/>Registrar</button>}><div className="formGrid"><select value={f.vehicle_id} onChange={e=>setF({...f,vehicle_id:e.target.value})}><option value="">Veículo</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.plate} · {v.brand} {v.model}</option>)}</select><select value={f.service_id} onChange={e=>{const sv=services.find(s=>s.id===e.target.value);setF({...f,service_id:e.target.value,charged_amount:sv?finalPrice(sv):''})}}><option value="">Serviço</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} · {money(finalPrice(s))}</option>)}</select><select value={f.employee_id} onChange={e=>setF({...f,employee_id:e.target.value})}><option value="">Funcionário responsável</option>{employees.filter(e=>e.active!==false).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option value="em_andamento">Em andamento</option><option value="concluido">Concluído</option></select><input type="number" placeholder="Valor cobrado" value={f.charged_amount} onChange={e=>setF({...f,charged_amount:e.target.value})}/><select value={f.payment_method_id} onChange={e=>setF({...f,payment_method_id:e.target.value})}><option value="">Forma de pagamento</option>{paymentMethods.filter(p=>p.active!==false).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input placeholder="Observações" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/><label className="file"><Camera size={17}/>Anexar imagens<input type="file" multiple accept="image/*" onChange={e=>setF({...f,files:e.target.files})}/></label></div></Panel><Panel title="Histórico de serviços"><Table headers={['Data','Veículo','Serviço','Funcionário','Valor','Status','Fotos','WhatsApp']}>{orders.map(o=><tr key={o.id}><td>{dt(o.completed_at||o.created_at)}</td><td>{vehicles.find(v=>v.id===o.vehicle_id)?.plate||'-'}</td><td>{services.find(s=>s.id===o.service_id)?.name||'-'}</td><td>{employees.find(e=>e.id===o.employee_id)?.name||o.performed_by||'-'}</td><td>{money(o.charged_amount||finalPrice(services.find(s=>s.id===o.service_id)))}</td><td><Status value={o.status}/></td><td>{images.filter(i=>i.service_order_id===o.id).length}</td><td>{o.status==='concluido'&&<button className="whatsapp" onClick={()=>whatsapp(o)}><MessageCircle size={16}/>Avisar</button>}</td></tr>)}</Table></Panel></section>}

function Appointments({appointments,clients,vehicles,services,canWrite,insert,update,remove,setAppointments}){const empty={client_id:'',vehicle_id:'',service_id:'',scheduled_at:'',notes:'',status:'agendado'};const [f,setF]=useState(empty),[edit,setEdit]=useState(null);const available=vehicles.filter(v=>!f.client_id||v.client_id===f.client_id);async function save(){if(!f.client_id||!f.vehicle_id||!f.service_id||!f.scheduled_at)return alert('Preencha cliente, veículo, serviço e data/hora.');if(edit)await update('appointments',edit,{...f,scheduled_at:new Date(f.scheduled_at).toISOString()},setAppointments,'Editou agendamento');else await insert('appointments',{...f,scheduled_at:new Date(f.scheduled_at).toISOString()},setAppointments,'Criou agendamento');setF(empty);setEdit(null)}return <section><Panel title="Agendamento de lavagens" action={canWrite&&<button className="primary" onClick={save}><CalendarDays size={17}/>{edit?'Salvar':'Agendar'}</button>}><div className="formGrid"><select value={f.client_id} onChange={e=>setF({...f,client_id:e.target.value,vehicle_id:''})}><option value="">Cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={f.vehicle_id} onChange={e=>setF({...f,vehicle_id:e.target.value})}><option value="">Veículo</option>{available.map(v=><option key={v.id} value={v.id}>{v.plate} · {v.brand} {v.model}</option>)}</select><select value={f.service_id} onChange={e=>setF({...f,service_id:e.target.value})}><option value="">Serviço</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input type="datetime-local" value={f.scheduled_at} onChange={e=>setF({...f,scheduled_at:e.target.value})}/><select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option value="agendado">Agendado</option><option value="confirmado">Confirmado</option><option value="em_atendimento">Em atendimento</option><option value="concluido">Concluído</option><option value="cancelado">Cancelado</option></select><input placeholder="Observações" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></div></Panel><Panel title="Agenda"><Table headers={['Data/Hora','Cliente','Veículo','Serviço','Status','Observação','Ações']}>{appointments.map(a=><tr key={a.id}><td>{dt(a.scheduled_at)}</td><td>{clients.find(c=>c.id===a.client_id)?.name||'-'}</td><td>{vehicles.find(v=>v.id===a.vehicle_id)?.plate||'-'}</td><td>{services.find(s=>s.id===a.service_id)?.name||'-'}</td><td><Status value={a.status}/></td><td>{a.notes||'-'}</td><td>{canWrite&&<Actions onEdit={()=>{setEdit(a.id);setF({...a,scheduled_at:new Date(a.scheduled_at).toISOString().slice(0,16)})}} onDelete={()=>remove('appointments',a.id,setAppointments,'Excluiu agendamento')}/>}</td></tr>)}</Table></Panel></section>}

function Employees({employees,orders,canAdmin,insert,update,remove,setEmployees}){const empty={name:'',phone:'',position:'',commission_percent:'0',active:true};const [f,setF]=useState(empty),[edit,setEdit]=useState(null);async function save(){if(!f.name)return alert('Informe o nome.');const p={...f,commission_percent:Number(f.commission_percent||0)};if(edit)await update('employees',edit,p,setEmployees,'Editou funcionário');else await insert('employees',p,setEmployees,'Cadastrou funcionário');setF(empty);setEdit(null)}return <section><Panel title="Equipe e comissões" action={canAdmin&&<button className="primary" onClick={save}><Save size={17}/>{edit?'Salvar':'Cadastrar'}</button>}><div className="formGrid"><input placeholder="Nome" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="Telefone" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/><input placeholder="Função" value={f.position} onChange={e=>setF({...f,position:e.target.value})}/><input type="number" placeholder="Comissão (%)" value={f.commission_percent} onChange={e=>setF({...f,commission_percent:e.target.value})}/></div><Table headers={['Nome','Função','Telefone','Comissão','Total gerado','Comissão estimada','Ações']}>{employees.map(e=>{const eo=orders.filter(o=>o.employee_id===e.id&&o.status==='concluido'),total=eo.reduce((s,o)=>s+Number(o.charged_amount||0),0);return <tr key={e.id}><td>{e.name}</td><td>{e.position||'-'}</td><td>{e.phone||'-'}</td><td>{e.commission_percent||0}%</td><td>{money(total)}</td><td><b>{money(total*Number(e.commission_percent||0)/100)}</b></td><td>{canAdmin&&<Actions onEdit={()=>{setEdit(e.id);setF({name:e.name||'',phone:e.phone||'',position:e.position||'',commission_percent:e.commission_percent||0,active:e.active!==false})}} onDelete={()=>remove('employees',e.id,setEmployees,'Excluiu funcionário')}/>}</td></tr>})}</Table>{!canAdmin&&<p className="hint">Somente o gerente pode alterar a equipe e os percentuais de comissão.</p>}</Panel></section>}

function Cash({payments,paymentMethods,orders,cashClosings,canAdmin,insert,remove,setCashClosings,setPaymentMethods}){const [day,setDay]=useState(new Date().toISOString().slice(0,10)),[methodName,setMethodName]=useState('');const daily=payments.filter(p=>String(p.paid_at).slice(0,10)===day);const total=daily.reduce((s,p)=>s+Number(p.amount||0),0);const byMethod=paymentMethods.map(m=>({name:m.name,total:daily.filter(p=>p.payment_method_id===m.id).reduce((s,p)=>s+Number(p.amount||0),0)})).filter(x=>x.total>0);async function close(){if(!canAdmin)return;const existing=cashClosings.find(c=>c.closing_date===day);if(existing)return alert('Esse dia já possui fechamento registrado.');await insert('cash_closings',{closing_date:day,total_amount:total,details:byMethod,closed_at:new Date().toISOString()},setCashClosings,'Realizou fechamento de caixa')}
 async function addMethod(){if(!methodName.trim())return;await insert('payment_methods',{name:methodName.trim(),active:true},setPaymentMethods,'Cadastrou forma de pagamento');setMethodName('')}
 return <section>{canAdmin&&<Panel title="Formas de pagamento" action={<button className="primary" onClick={addMethod}><Plus size={17}/>Adicionar</button>}><div className="formGrid two"><input placeholder="Ex.: PIX, Dinheiro, Cartão" value={methodName} onChange={e=>setMethodName(e.target.value)}/></div><div className="methodChips">{paymentMethods.map(m=><span key={m.id}>{m.name}<button onClick={()=>remove('payment_methods',m.id,setPaymentMethods,'Excluiu forma de pagamento')}><X size={14}/></button></span>)}</div></Panel>}<Panel title="Fechamento de caixa" action={<div className="inline"><input className="dateInput" type="date" value={day} onChange={e=>setDay(e.target.value)}/>{canAdmin&&<button className="primary" onClick={close}><Wallet size={17}/>Fechar caixa</button>}</div>}><div className="cashSummary"><div><span>Total do dia</span><strong>{money(total)}</strong></div>{byMethod.map(x=><div key={x.name}><span>{x.name}</span><strong>{money(x.total)}</strong></div>)}</div><Table headers={['Data/Hora','Forma','Valor','Ordem']}>{daily.map(p=><tr key={p.id}><td>{dt(p.paid_at)}</td><td>{paymentMethods.find(m=>m.id===p.payment_method_id)?.name||'-'}</td><td>{money(p.amount)}</td><td>{orders.find(o=>o.id===p.service_order_id)?.id?.slice(0,8)||'-'}</td></tr>)}</Table></Panel><Panel title="Fechamentos anteriores"><Table headers={['Data','Fechado em','Total']}>{cashClosings.map(c=><tr key={c.id}><td>{dateOnly(c.closing_date)}</td><td>{dt(c.closed_at)}</td><td><b>{money(c.total_amount)}</b></td></tr>)}</Table></Panel></section>}

function Reports({clients,vehicles,services,orders,employees,payments,paymentMethods}){const [from,setFrom]=useState(''),[to,setTo]=useState('');const filtered=orders.filter(o=>(!from||String(o.created_at).slice(0,10)>=from)&&(!to||String(o.created_at).slice(0,10)<=to));const rows=filtered.map(o=>{const v=vehicles.find(v=>v.id===o.vehicle_id),c=clients.find(c=>c.id===v?.client_id),s=services.find(s=>s.id===o.service_id),e=employees.find(e=>e.id===o.employee_id);return {Data:dt(o.completed_at||o.created_at),Cliente:c?.name||'',Placa:v?.plate||'',Veiculo:`${v?.brand||''} ${v?.model||''}`.trim(),Servico:s?.name||'',Funcionario:e?.name||o.performed_by||'',Valor:Number(o.charged_amount||finalPrice(s)),Status:o.status||''}});function pdf(){const doc=new jsPDF({orientation:'landscape'});doc.setFontSize(18);doc.text('Relatório de Serviços - Estética Veicular',14,16);doc.setFontSize(10);doc.text(`Período: ${from||'início'} a ${to||'hoje'} | Total: ${money(rows.reduce((s,r)=>s+r.Valor,0))}`,14,23);autoTable(doc,{startY:28,head:[['Data','Cliente','Placa','Veículo','Serviço','Funcionário','Valor','Status']],body:rows.map(r=>[r.Data,r.Cliente,r.Placa,r.Veiculo,r.Servico,r.Funcionario,money(r.Valor),r.Status])});doc.save('relatorio-servicos.pdf')}function excel(){const wb=XLSX.utils.book_new();const ws=XLSX.utils.json_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,'Serviços');const payRows=payments.map(p=>({Data:dt(p.paid_at),Forma:paymentMethods.find(m=>m.id===p.payment_method_id)?.name||'',Valor:Number(p.amount||0)}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(payRows),'Pagamentos');XLSX.writeFile(wb,'relatorio-estetica-veicular.xlsx')}
 return <section><Panel title="Relatórios PDF e Excel" action={<div className="reportBtns"><button className="secondary" onClick={pdf}><FileDown size={17}/>PDF</button><button className="primary" onClick={excel}><FileDown size={17}/>Excel</button></div>}><div className="formGrid two"><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="cashSummary"><div><span>Serviços no período</span><strong>{rows.length}</strong></div><div><span>Total de serviços</span><strong>{money(rows.reduce((s,r)=>s+r.Valor,0))}</strong></div></div><Table headers={['Data','Cliente','Placa','Serviço','Funcionário','Valor']}>{rows.map((r,i)=><tr key={i}><td>{r.Data}</td><td>{r.Cliente}</td><td>{r.Placa}</td><td>{r.Servico}</td><td>{r.Funcionario}</td><td>{money(r.Valor)}</td></tr>)}</Table></Panel></section>}

function UsersPanel({profiles,canAdmin,supabase,addLog,setProfiles}){const empty={full_name:'',email:'',password:'',role:'visualizador'};const [f,setF]=useState(empty),[busy,setBusy]=useState(false);async function create(){if(!canAdmin)return;if(!f.full_name||!f.email||f.password.length<6)return alert('Informe nome, e-mail e uma senha com pelo menos 6 caracteres.');setBusy(true);try{const {data,error}=await supabase.functions.invoke('create-user',{body:{...f,email:f.email.trim().toLowerCase()}});if(error)throw error;if(data?.error)throw new Error(data.error);setProfiles(x=>[...x,data.user]);await addLog(`Criou usuário ${f.email}`,'profiles',data.user.id);setF(empty);alert('Usuário criado com sucesso.')}catch(e){alert((e.message||'Não foi possível criar o usuário.')+'\n\nConfirme se a Edge Function create-user foi publicada no Supabase.')}finally{setBusy(false)}}return <section><Panel title="Usuários do sistema" action={canAdmin&&<button className="primary" disabled={busy} onClick={create}><Plus size={17}/>{busy?'Criando...':'Criar usuário'}</button>}><div className="formGrid"><input placeholder="Nome completo" value={f.full_name} onChange={e=>setF({...f,full_name:e.target.value})}/><input type="email" placeholder="E-mail" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input type="password" placeholder="Senha inicial" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/><select value={f.role} onChange={e=>setF({...f,role:e.target.value})}><option value="gerente">Gerente</option><option value="administrativo">Administrativo</option><option value="visualizador">Visualizador</option></select></div><Table headers={['Nome','E-mail','Perfil']}>{profiles.map(p=><tr key={p.id}><td>{p.full_name}</td><td>{p.email||'-'}</td><td><Status value={p.role}/></td></tr>)}</Table>{!canAdmin&&<p className="hint">Somente o gerente pode criar usuários.</p>}<div className="roleGrid"><div><b>Gerente</b><p>Acesso total, usuários, serviços, equipe, comissões e fechamento de caixa.</p></div><div><b>Administrativo</b><p>Clientes, veículos, agendamentos e execução dos serviços.</p></div><div><b>Visualizador</b><p>Acesso para consulta, sem alterações.</p></div></div></Panel></section>}
function Audit({logs}){return <section><Panel title="Histórico de ações"><Table headers={['Data/Hora','Usuário','Ação','Tipo']}>{logs.map(l=><tr key={l.id}><td>{dt(l.created_at)}</td><td>{l.user_name||'-'}</td><td>{l.action}</td><td>{l.entity_type||'-'}</td></tr>)}</Table></Panel></section>}

createRoot(document.getElementById('root')).render(<App/>);
